config/routes.rb
Feeds::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  resources :feeds do
    member do
      get 'main' => "feeds#main"
    end
    resources :entries
  end

  post "/feeds/:feed_id/entries/simple" => "simple_entries#create"
  get "/api" => "pages#api"
  get "/import" => "pages#import"
  get "/home" => "pages#home"
  get "/icons" => "pages#icons"

end

app/views/pages/api/_entrycollection.html.erb
<h2>REST API: Entry Collection</h2>
<p> A Feed collection represents a list of a users' feeds.</p>

<a name="uri"></a> 
<h3>Collection URI </h3>
<pre>$ <%=feeds_url%>.json</pre>
<br>
<a name="properties"></a> 
<h3>Feed Properties (for each element in the collection) </h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Property</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>_id</td>
    <td>The unique identifier for the object </td>
  </tr>
  <tr>
    <td>Title (required) </td>
    <td>The title of the feed in question. </td>
  </tr>
  <tr>
    <td>Subtitle</td>
    <td>Extra information about. </td>
  </tr>
  <tr>
    <td>Source</td>
    <td>A link of the website where the content is pulled from.  In the case where this is ambiguous, please provide a description.</td>
  </tr>
  <tr>
    <td>Rights</td>
    <td>The rights pertaining the public permission to use contents of this feed.</td>
  </tr>
  <tr>
    <td>Tags</td>
    <td>Feed Tags</td>
  </tr>
  <tr>
    <td>Categories</td>
    <td>Feed Categories</td>
  </tr>
  <tr>
    <td>Icon</td>
    <td>A URL to a picture used to describe this feed.  The picture should be at least 100x100px.</td>
  </tr>
  <tr>
    <td>Updated (Not editable)</td>
    <td>Most recent time when a feed collection / entry was edited, added, or deleted.  </td>
  </tr>
  <tr>
    <td>Updated_at (Not editable)</td>
    <td>Most recent time when the feed element itself was edited or created. </td>
  </tr>
  <tr>
  <tr>
    <td>Created_at (Not Editable)</td>
    <td>The time when the feed element was created. </td>
  </tr>
  </tbody>
</table>
<a name="get"> </a>
<h3>Get</h3>
<p> Get the entire feed collection.  This will only get info on the feed collection, not the enries that belong to each feed.</p>
<pre>$ curl -G <%=feeds_url%>.json</pre>

<a name="post"> </a>
<h3>Post </h3>
<p> Create a new feed element.</p>
<pre>$ curl -X PPOST <%=feeds_url%>.json -d "title=awesomefeed&rights=microsoft"  </pre>
<div class="alert alert-error">
  This is not actually working, probably should be. 
</div>

<a name="delete"> </a>
<h3>Delete</h3>
<p>Deletes all feeds in the feed collection.  </p>
<pre>$ curl -X DELETE <%=feeds_url%>.json</pre>
<div class="alert alert-error">
  This is not actually working, probably should be. 
</div>

app/views/pages/api/_entryelement.html.erb
<h2>REST API: Entry Element</h2>
<p> A entry element represents the data for a specific entry.  It does not respresent the feed elements.  For the feed elements, go .
</p>

<a name="uri"></a>
<h3>Element URI </h3>
<br>

<a name="properties"></a>
<h3>Element Properties </h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Property</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>_id</td>
    <td>The unique identifier for the object </td>
  </tr>
  <tr>
    <td>Title (required) </td>
    <td>The title of the feed in question. </td>
  </tr>
  <tr>
    <td>Subtitle</td>
    <td>Extra information about. </td>
  </tr>
  <tr>
    <td>Source</td>
    <td>A link of the website where the content is pulled from.  In the case where this is ambiguous, please provide a description.</td>
  </tr>
  <tr>
    <td>Rights</td>
    <td>The rights pertaining the public permission to use contents of this feed.</td>
  </tr>
  <tr>
    <td>Tags</td>
    <td>Feed Tags</td>
  </tr>
  <tr>
    <td>Categories</td>
    <td>Feed Categories</td>
  </tr>
  <tr>
    <td>Icon</td>
    <td>A URL to a picture used to describe this feed.  The picture should be at least 100x100px.</td>
  </tr>
  <tr>
    <td>Updated (Not editable)</td>
    <td>Most recent time when a feed collection / entry was edited, added, or deleted.  </td>
  </tr>
  <tr>
    <td>Updated_at (Not editable)</td>
    <td>Most recent time when the feed element itself was edited or created. </td>
  </tr>
  <tr>
  <tr>
    <td>Created_at (Not Editable)</td>
    <td>The time when the feed element was created. </td>
  </tr>
  </tbody>
</table>

<a name="get"></a>
<h3>Get </h3>
<p> Get the feed element.  This will only get info on the feed element, not the enries that belong to the feed.  For those, see the entries page.</p>
<pre>$ curl -G <%=feeds_url%>.json</pre>

<a name="put"></a>
<h3>Put </h3>
<p> Replace the feed element.  This will not effect the entries that belong to the feed. </p>
<pre>$ curl -X PUT <%=feeds_url%>.json -d "title=awesomefeed&rights=microsoft"  </pre>
<div class="alert alert-error">
  This is not actually working, probably should be. 
</div>

<a name="delete"></a>
<h3>Delete</h3>
<p>Deletes the feed element.</p>
<pre>$ curl -X DELETE <%=feeds_url%>.json</pre>

app/views/pages/api/_feedcollection.html.erb
<h2>REST API: Feed Collection</h2>
<p> A Feed element represents the data for a feed.  It does not respresent the feed elements.  For the feed elements, go <%= link_to 'here', feed_entries_path(@feed) %>.
</p>

<a name="uri"></a> 
<h3>Element URI </h3>
<pre>$ <%=feed_url(Feed.first)%>.json</pre>
<br>
<a name="properties"></a> 
<h3>Element Properties </h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Property</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>_id</td>
    <td>The unique identifier for the object </td>
  </tr>
  <tr>
    <td>Title (required) </td>
    <td>The title of the feed in question. </td>
  </tr>
  <tr>
    <td>Subtitle</td>
    <td>Extra information about. </td>
  </tr>
  <tr>
    <td>Source</td>
    <td>A link of the website where the content is pulled from.  In the case where this is ambiguous, please provide a description.</td>
  </tr>
  <tr>
    <td>Rights</td>
    <td>The rights pertaining the public permission to use contents of this feed.</td>
  </tr>
  <tr>
    <td>Tags</td>
    <td>Feed Tags</td>
  </tr>
  <tr>
    <td>Categories</td>
    <td>Feed Categories</td>
  </tr>
  <tr>
    <td>Icon</td>
    <td>A URL to a picture used to describe this feed.  The picture should be at least 100x100px.</td>
  </tr>
  <tr>
    <td>Updated (Not editable)</td>
    <td>Most recent time when a feed collection / entry was edited, added, or deleted.  </td>
  </tr>
  <tr>
    <td>Updated_at (Not editable)</td>
    <td>Most recent time when the feed element itself was edited or created. </td>
  </tr>
  <tr>
  <tr>
    <td>Created_at (Not Editable)</td>
    <td>The time when the feed element was created. </td>
  </tr>
  </tbody>
</table>

<a name="get"></a> 
<h3>GET </h3>
<p> Get the feed element.  This will only get info on the feed element, not the enries that belong to the feed.  For those, see the entries page.</p>
<pre>$ curl -G <%=feed_url(@feed)%>.json</pre>

<a name="post"></a> 
<h3>POST </h3>
<p> Create a new feed. </p>
<pre>$ curl -X POST <%=feed_url(@feed)%>.json -d "title=awesomefeed&rights=microsoft"  </pre>
<div class="alert alert-error">
  This is not actually working, probably should be. 
</div>

app/views/pages/api/_feedelement.html.erb
<h2>REST API: Feed Element</h2>
<p> A entry element represents the data for a specific entry.  It does not respresent the feed elements.  For the feed elements, go .
</p>

<h3>Element URI </h3>
<br>
<h3>Element Properties </h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Property</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>_id</td>
    <td>The unique identifier for the object </td>
  </tr>
  <tr>
    <td>Title (required) </td>
    <td>The title of the feed in question. </td>
  </tr>
  <tr>
    <td>Subtitle</td>
    <td>Extra information about. </td>
  </tr>
  <tr>
    <td>Source</td>
    <td>A link of the website where the content is pulled from.  In the case where this is ambiguous, please provide a description.</td>
  </tr>
  <tr>
    <td>Rights</td>
    <td>The rights pertaining the public permission to use contents of this feed.</td>
  </tr>
  <tr>
    <td>Tags</td>
    <td>Feed Tags</td>
  </tr>
  <tr>
    <td>Categories</td>
    <td>Feed Categories</td>
  </tr>
  <tr>
    <td>Icon</td>
    <td>A URL to a picture used to describe this feed.  The picture should be at least 100x100px.</td>
  </tr>
  <tr>
    <td>Updated (Not editable)</td>
    <td>Most recent time when a feed collection / entry was edited, added, or deleted.  </td>
  </tr>
  <tr>
    <td>Updated_at (Not editable)</td>
    <td>Most recent time when the feed element itself was edited or created. </td>
  </tr>
  <tr>
  <tr>
    <td>Created_at (Not Editable)</td>
    <td>The time when the feed element was created. </td>
  </tr>
  </tbody>
</table>

<a name="get"></a> 
<h3>Get </h3>
<p> Get the feed element.  This will only get info on the feed element, not the enries that belong to the feed.  For those, see the entries page.</p>
<pre>$ curl -G <%=feeds_url%>.json</pre>

<a name="put"></a> 
<h3>Put </h3>
<p> Replace the feed element.  This will not effect the entries that belong to the feed. </p>
<pre>$ curl -X PUT <%=feeds_url%>.json -d "title=awesomefeed&rights=microsoft"  </pre>
<div class="alert alert-error">
  This is not actually working, probably should be. 
</div>

<a name="delete"></a> 
<h3>Delete</h3>
<p>Deletes the feed element.</p>
<pre>$ curl -X DELETE <%=feeds_url%>.json</pre>

app/views/pages/api/_nav.html.erb
<div class="well" style="position:fixed;padding:10px 0">
  <ul class="nav nav-list" >

    <li><%= link_to raw("<strong>Feed Collection</strong>"), api_path(:page => 'feedcollection') %></li>
    <li><%= link_to 'GET', api_path(:page => 'feedcollection', :anchor =>'get') %> </li>
    <li><%= link_to 'POST', api_path(:page => 'feedcollection', :anchor =>'post')  %> </li>
    <li class="divider"></li>
    <li><%= link_to raw("<strong>Feed Element</strong>"), api_path(:page => 'feedelement')  %> </li>
    <li><%= link_to 'GET', api_path(:page => 'feedelement', :anchor =>'get')  %> </li>
    <li><%= link_to 'PUT', api_path(:page => 'feedelement', :anchor =>'put')%> </li>
    <li class="divider"></li>
    <li><%= link_to raw("<strong>Entry Collection</strong>"), api_path(:page => 'entrycollection') %></li>
    <li><%= link_to 'GET', api_path(:page => 'entrycollection', :anchor =>'get') %> </li>
    <li><%= link_to 'PUT', api_path(:page => 'entrycollection', :anchor =>'put')%> </li>
    <li><%= link_to 'POST', api_path(:page => 'entrycollection', :anchor =>'post')%> </li>
    <li><%= link_to 'DELETE', api_path(:page => 'entrycollection', :anchor =>'delete') %> </li>
    <li class="divider"></li>
    <li><%= link_to raw("<strong>Entry Element</strong>"), api_path(:page => 'entryelement') %></li>
    <li><%= link_to 'GET', api_path(:page => 'entryelement', :anchor =>'get') %> </li>
    <li><%= link_to 'PUT', api_path(:page => 'entryelement', :anchor =>'put') %> </li>
    <li><%= link_to 'DELETE', api_path(:page => 'entryelement', :anchor =>'delete') %> </li>
  </ul>

</div>

app/views/pages/api/_overview.html.erb
<h3> Overview </h3>
<p> Liberation.io runs on a REST API with the two data types of Feeds and Entries. Each feed has many entries.  This documentation as well as the functionality are both still in development and are still highly buggy.</p>
<h3> REST Commands </h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Resource</th>
      <th>Exaple URI</th>
      <th>GET</th>
      <th>PUT</th>
      <th>POST</th>
      <th>DELETE</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>  <i class="icon-folder-close"></i><i class="icon-reorder"></i></td>
    <td>Feed Collection</td>
    <td> /feeds.json </td>
    <td> <strong>List</strong> the URIs and other details of all feeds.</td>
    <td> X </td>
    <td> <strong>Create</strong> a new feed.</td>
    <td> X </td>
  </tr> 
  <tr>
    <td> <i class="icon-folder-close"></i><i class="icon-circle"></i></td>
    <td> Feed Element  </td>
    <td> /feeds/7sdf7.json </td>
    <td> <strong> Retrieve </strong> all metadata about the feed object</td>
    <td> <strong> Replace </strong> the metadata about the feed object. </td>
    <td> X </td>
    <td> <strong> Delete </strong> the feed element. </td>
  </tr> 
  <tr>
    <td> <i class="icon-file-alt"></i><i class="icon-reorder"></i></td>
    <td>Entry Collection  </td>
    <td> /feeds/7sdf7/entries.json </td>
    <td> <strong> List </strong> the URIs and info on all entries for a specific feed.</td>
    <td> <strong> X </strong> </td>
    <td> <strong>Create</strong> a new entry.</td>
    <td> <strong> X </strong> </td>
  </tr> 
  <tr>
    <td><i class="icon-file-alt"></i><i class="icon-circle"></i></td>
    <td> Entry Element  </td>
    <td> /feeds/7sdf7/entries/23f2r.json </td>
    <td> <strong> Retrieve </strong> all information about a specific entry. </td>
    <td> <strong> Replace </strong> all information about the feed entry. </td>
    <td> <strong> X </strong></td>
    <td> <strong> Delete </strong> the entry. </td>
  </tr> 
  </tbody>
</table>