config/routes.rb
Feeds::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  resources :feeds do
    member do
      get 'main' => "feeds#main"
    end
    resources :entries
  end

  post "/feeds/:feed_id/entries/simple" => "simple_entries#create"
  get "/api" => "pages#api"
  get "/import" => "pages#import"
  get "/home" => "pages#home"
  get "/icons" => "pages#icons"

end

app/models/feed.rb
class Feed
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :subtitle, type: String
  field :updated, type: DateTime, default: Time.now
  field :source, type: String
  field :rights, type: String
  field :tags, type: Array
  field :categories, type: Hash
  field :icon, type: String

  attr_accessible :title, :subtitle, :updated, :source, :rights, :tags, :categories, :icon, :author_attributes, :author, :user_id
  validates_presence_of :title
  has_many :entries
  belongs_to :user

  embeds_one :author, autobuild: true
  accepts_nested_attributes_for :author

  def update!
    a = self
    a.updated = Time.now.utc
    a.save
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @user = current_user
    @feeds = @user.feeds.order_by(:updated.desc)
    respond_to do |format|
      format.html {render :layout => 'standard'}
      format.json { render json: @feeds.order_by(:updated_desc) }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feeds = Feed.order_by(:updated.desc).limit(10)
    @feed = Feed.find(params[:id])
    @entries = @feed.entries.order_by(:published.desc).limit(20)
    @user = current_user if current_user
    respond_to do |format|
      format.html {render :layout => 'standard'}
      format.json { render json: @feed }
      format.atom {render :layout => false }
    end
  end

  def main
    @feeds = Feed.order_by(:updated.desc).limit(10)
    @feed = Feed.find(params[:id])
    @entries = @feed.entries.order_by(:published.desc).limit(20)
    respond_to do |format|
      format.html {render :layout => 'standard'}
      format.json { render json: @feed }
      format.atom {render :layout => false }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @user = current_user
    @feed = Feed.new
    @feed.build_author
    respond_to do |format|
      format.html {render :layout => 'standard'}
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
    render :layout => 'feed'
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(params[:feed])
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])
    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper

  def updated_s(feed)
    diff = Time.now - feed.updated
    "uptdate #{distance_of_time_in_words(diff)} ago"
  end
end

app/views/feeds/element/_buttons.html.erb
<div class="btn-group" style="float:right">
  <button class="btn" href="#edit" data-toggle="pill"><i class="icon-pencil"></i></a> </button>
<%= button_tag feed_path(@feed), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do %>
  <i class="icon-remove"></i>
    <% end %>
    </div>

app/views/feeds/element/_header.html.erb
<div class="well">
  <div class="row">
    <div class="span7">
      <img src="<%=@feed.icon%>" class="img-rounded pull-left" style="width:100px; margin-right:20px">
      <h3><%= link_to @feed.title, @feed %> </h3>
      <h4><%= @feed.subtitle %> </h4>
    </div>

    <div class="btn-toolbar" style="float:right">
      <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i> <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li> <%= link_to raw('<i class="icon-reorder"></i>Info'), main_feed_path(@feed) %></li>
          <li> <%= link_to raw('<i class="icon-pencil"></i>Edit'), edit_feed_path(@feed) %></li>
        </ul>
      </div><!-- /btn-group -->

      <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown"><i class="icon-share-alt"></i> <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#"><i class="icon-cog"></i>API</a></li>
          <li class="divider"></li>
          <li><%= link_to raw('<i class="icon-reorder"></i>Json'), feed_path(@feed, :format => :json) %></li>
          <li><%= link_to raw('<i class="icon-rss"></i>Atom'), feed_path(@feed, :format => :atom) %></li>
        </ul>
      </div><!-- /btn-group -->

      <%= link_to feed_path(@feed), :class => "btn btn-danger", :method => :delete, data: {confirm: "This will delete the entire feed.  Are you sure you want to do this?"} do %>
        <i class="icon-remove"></i>
    <% end %>
    </div>
  </div>
</div>

app/views/feeds/element/_main.html.erb
<div class="well">
  <h3><%= link_to raw('<i class="icon-reply"></i>'), feed_path(@feed) %>
  &nbsp;
    &nbsp;&nbsp;<i class="icon-info-sign"></i>&nbsp;Feed Information
    <div class="btn-toolbar" style="float:right; margin:0px">
      <div class="btn-group" style="margin-top:4px" >
        <a class="btn tab-default" href="#table" data-toggle="tab" ><i class="icon-table"></i></a>
        <a class="btn" href="#serializable" data-toggle="tab">{ }</a>
      </div>
      <a class="btn" href="#edit" data-toggle="tab"><i class="icon-pencil"></i> Edit</a>
    </div>

  </h3>
  <div class="tab-content">
    <div class="tab-pane" id="min">
    </div>
    <div class="tab-pane" id="table">
      <%= render 'feeds/element/table.html.erb' %>
    </div>
    <div class="tab-pane" id="serializable">
      <%= @feed.to_json %>
    </div>
    <div class="tab-pane" id="edit">
      <%= render 'feeds/form.html.erb' %>
    </div>
  </div>
</div>

app/views/feeds/element/_summary.html.erb
<div class="row">
  <div class="span10">
    <div class="row">
      <div class="span3">
        <h4> Feed Info </h4>
        <%= @feed.source%>
      </div>
      <div class="span3">
        <h4> Feed Entries Info </h4>
        Count: <%= link_to (@feed.entries.count.to_s + " Entries"), feed_entries_path(@feed) %></br>
        Most Recent: <%= @feed.updated.strftime("%m/%d/%Y %I:%M%p") %>
      </div>
      <div class="span3">
        <h4> Remixer </h4>
        <%= @feed.author.name%></br> <%= @feed.author.email%> </br><%= @feed.author.uri %>
      </div>
    </div>
  </div>
</div>

</br>
</br>
<h3><i class="icon-list"></i> Recent Feed Entries </h3>
</br>
 <div class="tab-content">
      <div class="tab-pane" id="table">
        <%= render 'feeds/element/table.html.erb' %>
      </div>
    </div>

<table class="table table-bordered">
  <tr>
    <th>published</th>
    <th>id</th>
    <th>title</th>
    <th>summary</th>
    <th>link</th>
    <th>content</th>
    <th>author</th>
  </tr>

  <%@entries.each do |entry| %>
    <tr>
    <td><%= entry.published.strftime("%m/%d/%Y %I:%M%p")  %></td>
    <td><%= link_to entry.id, feed_entry_path(entry.feed_id,entry) %></td>
    <td><%= entry.title %></td>
    <td><%= entry.summary %></td>
    <td><%= entry.link %></td>
    <td><%= entry.content %></td>
    <td><%= entry.author.name %></td>
    <td>
      <% unless entry.published === entry.updated %>
        <%= entry.updated.strftime("%m/%d/%Y %I:%M%p")%>
    <% end %>
    </td>
    <td><%= link_to raw('<i class="icon-pencil"></i>'), edit_feed_entry_path(entry.feed, entry) %></td>
    <td><%= link_to raw('<i class="icon-remove"></i>'), feed_entry_path(entry.feed, entry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

<% end %>

</table>

app/views/feeds/element/_table.html.erb
<h3><i class="icon-globe"></i>  Feed Table </h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Property</th>
      <th>Content</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>_id</td>
    <td><%= @feed.id %></td>
  </tr>
  <tr>
    <td>Title (required) </td>
    <td><%= @feed.title %></td>
  </tr>
  <tr>
    <td>Subtitle</td>
    <td><%= @feed.subtitle %></td>
  </tr>
  <tr>
    <td>Source</td>
    <td><%= @feed.source %></td>
  </tr>
  <tr>
    <td>Rights</td>
    <td><%= @feed.rights %></td>
  </tr>
  <tr>
    <td>Tags</td>
    <td><%= @feed.tags %></td>
  </tr>
  <tr>
    <td>Categories</td>
    <td><%= @feed.categories %></td>
  </tr>
  <tr>
    <td>Icon</td>
    <td><%= @feed.icon %></td>
  </tr>
  <tr>
    <td>Updated (Not editable)</td>
    <td><%= @feed.updated %></td>
  </tr>
  <tr>
    <td>Updated_at (Not editable)</td>
    <td><%= @feed.updated_at %></td>
  </tr>
  <tr>
  <tr>
    <td>Created_at (Not Editable)</td>
    <td><%= @feed.created_at %></td>
  </tr>
  </tbody>
</table>
</br>
<h3> <i class="icon-user"></i> Author Table </h3>
<table class="table table-bordered">
  <tr class="info">
    <th>id</th>
    <th>name</th>
    <th>email</th>
    <th>uri</th>

  </tr>
  <tr>
    <td><%= @feed.author.id %> </td>
    <td><%= @feed.author.name %> </td>
    <td><%= @feed.author.email %> </td>
    <td><%= @feed.author.uri %> </td>
  </tr>
</table>