config/routes.rb
Feeds::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  resources :feeds do
    member do
      get 'main' => "feeds#main"
    end
    resources :entries
  end

  post "/feeds/:feed_id/entries/simple" => "simple_entries#create"
  get "/api" => "pages#api"
  get "/import" => "pages#import"
  get "/home" => "pages#home"
  get "/icons" => "pages#icons"

end

app/models/entry.rb
class Entry
  include Mongoid::Document
  attr_accessible :title, :updated, :published, :content, :link, :summary, :dump, :author
  field :title, type: String
  field :updated, type: DateTime, default: Time.now
  field :published, type: DateTime, default: Time.now
  field :content, type: String
  field :link, type: String
  field :summary, type: String
  field :dump, type: Hash

  validates_presence_of :title, :published
  belongs_to :feed

  embeds_one :author, autobuild: true
  accepts_nested_attributes_for :author

  after_save :update_feed

  def update_feed
    feed.update!
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @feed = Feed.find(params[:feed_id])
    @entries = @feed.entries
    respond_to do |format|
      format.html { render :layout => 'feed'}
      format.json { render json: @entries.order_by(:published.desc), :root => false }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @feed = Feed.find(params[:feed_id])
    @entry = Entry.find(params[:id])
    respond_to do |format|
      format.html { render :layout => 'feed'}
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @feed = Feed.find(params[:feed_id])
    @entry = @feed.entries.new
    respond_to do |format|
      format.html { render :layout => 'feed'}
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @feed = Feed.find(params[:feed_id])
    @entry = Entry.find(params[:id])
    render :layout => 'standard'
  end

  # POST /entries
  # POST /entries.json
  def create
    @feed = Feed.find(params[:feed_id])
    @entry = @feed.entries.new(params[:entry])

    respond_to do |format|
      if @entry.save
        @entry.author.save
        format.html { redirect_to feed_entry_path(@feed,@entry), notice: 'Entry was successfully created.' }
        format.json { render json: feed_entry_path(@feed, @entry), status: :created, location: feed_entry_path(@feed, @entry) }
      else
        format.html { render action: "new" }
        format.json { render json: feed_entry_path(@feed,@entry).errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])
    @feed = @entry.feed

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to feed_entry_path(@feed, @entry), notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @feed = @entry.feed
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to feed_path(@feed) }
      format.json { head :no_content }
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/collection/_blog.html.erb
<% @entries.each do |entry|%>
  <%= render '/entries/element/blog.html.erb', :entry => entry %>
<% end %>

app/views/entries/collection/_list.html.erb
<% @entries.each do |entry| %>
  <dl class="dl-horizontal" >
    <dt><h5>title</h5></dt>
    <dd><h5><%=entry.title%></h5></dd>
  <dt>id</dt>
  <dd><%=entry.id%></dd>
  <dt>summary</dt>
  <dd><%=entry.summary%></dd>
  <dt>link</dt>
  <dd><%=entry.link%></dd>
  <dt>content</dt>
  
  <dd><%= (entry.content)%></dd>
  <dt>published</dt>
  <dd><%=entry.published%></dd>
  <dt>updated</dt>
  <dd><%=entry.updated%></dd>
  <dt>dump</dt>
  <dd>
  <% if entry.dump and !entry.dump.empty? %>
    <table class="table span5 table-bordered" style="margin-left:0px">
    <% entry.dump.each_pair do |key,value| %>
      <tr>
      <td> <strong> <%= key %> </strong> </td>
      <td> <%= raw(value) %> </td>
    </tr>
  <% end %>
  </table>
<% end %>
  </dd>

  <dt>author</dt>
  <dd>
  <table class="table span5 table-bordered" style="margin-left:0px">
    <tr>
      <td> <strong> Name </strong> </td>
      <td> <%= entry.author.name %> </td>
    </tr>
    <tr>
      <td> <strong> Email<strong> </td>
          <td> <%= entry.author.email %> </td>
        </tr>
        <tr>
          <td> <strong> Uri <strong> </td>
              <td> <%= entry.author.uri %> </td>
            </tr>
          </table>
        </dl>
        <hr>
      <% end %>

app/views/entries/collection/_main.html.erb
<div class="well" style="padding-top:3px">
  <h3>Entries
    <div class="btn-toolbar" style="float:right; margin:0px">
      <div class="btn-group" style="margin-top:4px" >
        <a class="btn tab-default" href="#blog" data-toggle="tab"><i class="icon-th-large"></i></a>
        <a class="btn" href="#standard" data-toggle="tab"><i class="icon-align-justify"></i></a>
        <a class="btn" href="#list" data-toggle="tab"><i class="icon-columns"></i></a>
        <a class="btn" href="#serializable" data-toggle="tab">{ }</a>
      </div>
      <%= link_to new_feed_entry_path(@feed), :class => "btn btn-success" do %>
        <i class="icon-plus"></i> New
    <% end %>
    </div>
  </h3>
  <hr style="margin:4px 0 4px 0">

  <div class="tab-content">

    <div class="tab-pane" id="standard">
      <%= render 'entries/collection/standard.html.erb' %>
    </div>
    <div class="tab-pane" id="serializable">
      <%= render 'entries/collection/serializable.html.erb' %>
    </div>
    <div class="tab-pane" id="list">
      <%= render 'entries/collection/list.html.erb' %>
    </div>
    <div class="tab-pane" id="blog">
      <%= render 'entries/collection/blog.html.erb' %>
    </div>
  </div>
</div>

app/views/entries/collection/_serializable.html.erb
<% @entries.each do |entry|%>
  <%= entry.to_json %>
  <br>
  <br>
<% end %>

app/views/entries/collection/_standard.html.erb
<%= render @entries %>

app/views/entries/collection/_table.html.erb
<table class="table table-bordered">
  <tr>
    <th>published</th>
    <th>id</th>
    <th>title</th>
    <th>summary</th>
    <th>link</th>
    <th>content</th>
    <th>dump</th>
    <th>author</th>
    <th>edit</th>
  </tr>

  <%@entries.each do |entry| %>
    <tr>
    <td><%= entry.published.strftime("%m/%d/%Y %I:%M%p")  %></td>
    <td><%= link_to entry.id, feed_entry_path(entry.feed_id,entry) %></td>
    <td><%= entry.title %></td>
    <td><%= entry.summary %></td>
    <td><%= entry.link %></td>
    <td><%= entry.content %></td>
    <td><%= entry.dump %></td>
    <td><%= entry.author.name %></td>
    <td>
      <% unless entry.published === entry.updated %>
        <%= entry.updated.strftime("%m/%d/%Y %I:%M%p")%>
    <% end %>
    </td>
    <td><%= link_to raw('<i class="icon-pencil"></i>'), edit_feed_entry_path(entry.feed_id, entry) %></td>
    <td><%= link_to raw('<i class="icon-remove"></i>'), feed_entry_path(entry.feed_id, entry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

<% end %>

</table>