config/routes.rb
Feeds::Application.routes.draw do

  devise_for :users

  root :to => "pages#home"
  resources :feeds do
    member do
      get 'main' => "feeds#main"
    end
    resources :entries
  end

  post "/feeds/:feed_id/entries/simple" => "simple_entries#create"
  get "/api" => "pages#api"
  get "/import" => "pages#import"
  get "/home" => "pages#home"
  get "/icons" => "pages#icons"

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top" style="margin-bottom:50px;">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Feedhaven", home_path, :class => "brand" %>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to raw('<i class="icon-cogs"></i> API'), api_path %></li>
          <li><a href="http://feedhaven.org/warnings"> <i class="icon-remove-sign"></i>Warnings </a></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to raw('<i class="icon-cloud"></i> Feeds'), feeds_path %></li>
            <li><%= link_to raw('<i class="icon-plus"></i> New'), new_feed_path %></li>
            <li><%= link_to raw('<i class="icon-user"></i> Logout'), destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li> <%= link_to(raw('<i class="icon-user"></i>Login'), new_user_session_path) %> </li>
        <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<ul class="nav nav-pills nav-stacked">

  <% if current_user %>
  <li class="nav-header">Recent Feeds</li>
  <% current_user.feeds.order_by(:updated.desc).limit(10).each do |feed| %>
    <% active = (@feed && (feed.id == @feed.id)) ? 'active' : '.'%>
  <li class=<%= active %>>
  <%= link_to raw(feed.title.to_s), feed%>
  </li>
<% end %>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href='http://fonts.googleapis.com/css?family=Germania+One|Bangers' rel='stylesheet' type='text/css'>
<title><%= content_for?(:title) ? yield(:title) : "Feeds" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>


</head>
<body>

<%= render 'layouts/header' %>
<div class="container" style="margin-top:45px">
      <%= bootstrap_flash %>
      <%= yield %>
  <footer>
  </footer>

</div> <!-- /container -->

<!-- Javascripts
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/layouts/feed.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Feeds" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>


</head>
<body>

<%= render 'layouts/header' %>
<div class="container" style="margin-top:55px">
      <div class="row">
  <div class="span2">
    <%= render 'layouts/nav.html.erb'%>
  </div>
  <div class='span10'>
    <%= render 'feeds/element/header.html.erb' %>
      <%= bootstrap_flash %>
      <%= yield %>
  </div>
</div>




  <footer>
  </footer>

</div> <!-- /container -->

<!-- Javascripts
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Feeds" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>


</head>
<body>

<%= render 'layouts/header' %>
<div class="container" style="margin-top:55px">
      <div class="row">
  <div class="span2">
    <%= render 'layouts/nav.html.erb'%>
  </div>
  <div class='span10' ">
      <%= bootstrap_flash %>
      <%= yield %>
  </div>
</div>

  <footer>
  </footer>

</div> <!-- /container -->

<!-- Javascripts
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>